###############

GPU: [0]

VERBOSE: True

MODEL:
  MODE: 'Denoising'
  SESSION: 'NAFNet'

# Optimization arguments.
# 8gpus*8bs*256*256*400000iters
OPTIM:
  BATCH_SIZE: 8
  T_MAX: 3200000
  NUM_ITERS: 3200000
  LR_INITIAL: 0.000125
  #NEPOCH_DECAY: [40]
  #BETA1: 0.9

TRAINING:
  TRAIN_PS: 256
  VAL_PS: 196
  RESUME: False
  RESUME_PATH: ''
  PRINT_FREQ: 20
  TRAIN_DIR: 'SIDD_Data/train' # path to training data
  VAL_DIR: 'SIDD_Data/val'     # path to validation data
  SAVE_DIR: './output/'          # path to save models and images
  SAVE_IMAGES: False
  #VAL_AFTER_EVERY: 1

